### PR TITLE
Refactor archive and fix archive errors 

### LINKED ISSUE #48: extracted archives not working
I'm trying to use the --archive option to read a directory instead of a zip file but it doesn't work.  I've tried a few variations to the path spec like ./slackarchives and /code/slackarchives and /code/slackarchives/ to no avail. 

```
# slack-export-viewer --archive ./slackarchives/
Traceback (most recent call last):
  File "/usr/local/bin/slack-export-viewer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/slackviewer/main.py", line 60, in main
    configure_app(app, archive, debug)
  File "/usr/local/lib/python3.6/site-packages/slackviewer/main.py", line 34, in configure_app
    path = extract_archive(archive)
  File "/usr/local/lib/python3.6/site-packages/slackviewer/archive.py", line 49, in extract_archive
    raise TypeError("{} is not a zipfile".format(filepath))
TypeError: /slackarchives/ is not a zipfile
```
This seems to be a problem with [https://github.com/hfaran/slack-export-viewer/blob/0.2.0/slackviewer/archive.py#L47](archive.py#L47).  I might eventually get around to fixing this once I need to merge multiple slack exports.

### PR DESCRIPTION
**Pull request by tscritch**
- Refactored the archive file into two seperate files: archive.py and reader.py

- Reader is a class that can read all of the data from the json files and make it usefull for the view of the app

- Reader class stores all of the empty directories of dms and gets the list on every startup of the app

Should resolve #48 and #58

### CODE REVIEW

**Comment by hfaran** [comment]
0.5.0 released

**Comment by depperson** [comment]
pip only shows up to version 0.4.2, can you release a newer version to pip?

**Comment by hfaran** [comment]
@depperson Not sure where you're looking; 0.6.0 is the latest version available on pypi: https://pypi.org/project/slack-export-viewer/0.6.0/#history

**Comment by depperson** [comment]
Weird.  I can see 0.6.0 on my laptop but inside my docker container I can only see up to 0.4.2.  I even upgraded pip inside the container to no avail.  I'll just point pip at github until I figure out the cause.  Thanks!

**Pull request merged**
